### ISSUE TITLE
NEXUS_CONTENT env variable not loaded

### ISSUE THREAD

**Issue by pchang388** [sonatype/nxrm3-helm-repository#39]
Chart: `nexus-repository-manager`
Chart version: `42.0.1`

Problem:
When trying to configure nexus behind ingress-nginx with a base path (`/nexus`), I always get 404 when hitting the UI:

![image](https://user-images.githubusercontent.com/51681873/212607629-3d9eeeb6-5553-415f-8ed6-aa654c0394ef.png)

I set the NEXUS_CONTENT env variable to:

```
nexus:
  docker:
    enabled: true
    # registries:
    #   - host: homelab
    #     port: 5000
    #     secretName: registry-secret
  env:
    # minimum recommended memory settings for a small, person instance from
    # https://help.sonatype.com/repomanager3/product-information/system-requirements
    - name: INSTALL4J_ADD_VM_PARAMS
      value: |-
        -Xms2703M -Xmx2703M
        -XX:MaxDirectMemorySize=2703M
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseCGroupMemoryLimitForHeap
        -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "true"
    - name: NEXUS_CONTEXT
      value: nexus
```

I also set the liveness and readiness probes to match:

```
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    timeoutSeconds: 10
    path: /nexus
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
    timeoutSeconds: 10
    path: /nexus
```

Ingress Rule:
```
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "homelab-selfsigned-issuer"
    # kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hostPath: /nexus(/|$)(.*)
  hostRepo: my-domain-name.home
```

But when accessing the UI, I can only see a 404 response. It appears I am missing some configuration or option, probably something simple I overlooked, does anyone have an idea by chance? This is usually straight forward with other apps and involves similar steps like seteting a ROOT_URL or path and then using ingress rules to add the path.

Any help is appreciated, thanks!
