### ISSUE TITLE
How to set logging level

### ISSUE THREAD

**Issue by chanwook-lee** [sonatype/nxrm3-helm-repository#54]
Hi, I'm going to set logging level of nexus repository,

in values.yaml, I set
```
nexus:
  properties:
    override: true
    data:
      root.level: ERROR
```
But, when I install nexus through helm, it couldn't work.

When after the pod run, 
root.level=ERROR is written in /nexus-data/etc/nexus.properties
![Screenshot 2023-09-19 at 6 07 04 PM](https://github.com/sonatype/nxrm3-helm-repository/assets/108053113/c1d97d28-5818-4d47-9c8e-b6090111a41d)

How can I fix it?
Thanks.
